# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rtag1jWqxYwPHA45m1eRrgyvTY6WOL74
"""

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/members.csv")
df = df.dropna()
df = df.iloc[:int(len(df)*0.7)]
print(int(df['f1'].quantile(.25)))

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/members.csv")
df_cntNull = df.isnull().sum()
df_cntNull = df_cntNull.sort_values(ascending=False)
print(df_cntNull.index[0])

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-1.csv")
q1 = df['age'].quantile(0.25)
q3 = df['age'].quantile(0.75)
result = abs(q1 - q3)
print(int(result))

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/data4-2.csv")
cond1 = (df['loves'] + df['wows']) / df['reactions'] > 0.4
cond2 = (df['loves'] + df['wows']) / df['reactions'] < 0.5
cond3 = df['type'] == 'video'
print(len(df[cond1 & cond2 & cond3]))

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/data5-2.csv")
df['bmi'] = df['Weight'] / (df['Height']/100)**2
cond1 = (df['bmi'] >= 18.5) & (df['bmi'] < 23)
cond2 = (df['bmi'] >= 23) & (df['bmi'] < 25)
print(abs(len(df[cond1]) - len(df[cond2])))

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/student_assessment.csv")
df = df.dropna()
id = df['id_assessment'].value_counts().idxmax()
cond = df['id_assessment'] == id
df = df[cond]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['score'] = scaler.fit_transform(df[['score']])
print(round(df['score'].max(), 3))